# Generated by Django 4.1.3 on 2024-02-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatat',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
