# Generated by Django 4.1.3 on 2024-02-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatat',
            new_name='avatar',
        ),
    ]
